name: demo-5
on:
  push:
    branches: [ main ]
jobs:
  run-with-mc:
    runs-on: ubuntu-latest
    steps:
      - name: Install MC
        run: sudo apt-get install mc -y
      - name: Say Hallo
        run: echo Hallo DevOpenSpace 2023
