name: demo-10 with varInStep
on:
  push:
    branches: [ main ]
    
jobs:
  jobSource:
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "varInStep=hello world" >> $GITHUB_OUTPUT
    outputs:
      greeting: ${{ steps.step1.outputs.varInStep }}
  jobTarget:
    runs-on: ubuntu-latest
    needs: jobSource
    steps:
    - run: echo ${{ needs.jobSource.outputs.greeting }}
